/** Medieval fantasy palette & typography for Wisp's Vigil. */
export const FantasyTheme = {
  colors: {
    bgDeep: 0x12100c,
    bgStone: 0x2a2420,
    bgArena: 0x1e1a16,
    grid: 0x3d352c,
    gridAccent: 0x4a4238,
    parchment: "#e8dcc4",
    parchmentDim: "#9a8b72",
    gold: "#d4a84b",
    goldBright: "#f0d080",
    arcane: "#c4b0f0",
    balefire: "#d45838",
    soulShard: "#6ecf8a",
    ward: "#8cb8d8",
    vitality: "#6ecf8a",
    plating: "#8cb8d8",
    urgent: "#e8a050",
    mute: "#6a5c4a",
    goldHex: 0xf0d080,
    arcaneHex: 0xb8a0e8,
    balefireHex: 0xd45838,
    soulHex: 0x6ecf8a,
    wardHex: 0x8cb8d8,
    flashWinHex: 0x6ecf8a,
    flashLoseHex: 0x8b2020,
  },
  fonts: {
    title: '"Cinzel", "Palatino Linotype", "Times New Roman", serif',
    body: '"Crimson Text", Georgia, "Times New Roman", serif',
    hud: '"Cinzel", Georgia, serif',
  },
  copy: {
    gameTitle: "WISP'S VIGIL",
    menuBody:
      "Hold the ward for 90 seconds.\nArcane bolts auto-seek the nearest foe.\nGather glory to choose weapon powers.\nAt the last sands, slay the Balefire Lord.\nDrag a finger or use WASD/arrows to move",
    menuStart: "Tap or press SPACE to begin the vigil",
    hudScore: "Glory",
    hudTime: "Sands",
    hudVitality: "Vitality",
    hudPlating: "Plating",
    pickupSoul: "+Glory",
    pickupVitality: "+Vitality",
    pickupPlating: "+Plating",
    gameOverWin: "THE VIGIL HELD!",
    gameOverLose: "THE WISP FADES",
    gameOverScore: (n: number) => `Glory earned: ${n}`,
    gameOverRestart: "SPACE or click — try the vigil again",
  },
} as const;
